### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by lighter** [getsentry/docker-sentry#143]
This is my docker-compose.yml. 

```
 ...
    postgres:
        build: ./postgres/
        volumes:
          - ./postgres/postgres-data:/var/lib/postgresql/data
...
    sentry:
        build: ./sentry/
        links:
          - postgres
          - redis
...
```

I used sentry version 8, postgres(9.6.3), redis(4). When I tried to recreate postgres container, I got this error message from postgres container.

```
postgres_1         | ERROR:  relation "sentry_option" does not exist at character 114
postgres_1         | STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= '2018-08-09 02:46:52.025848+00:00'
postgres_1         | ERROR:  relation "django_site" does not exist at character 78
postgres_1         | STATEMENT:  SELECT "django_site"."id", "django_site"."domain", "django_site"."name" FROM "django_site" WHERE "django_site"."id" = 1
```
