### ISSUE TITLE
Email notificaitions not sending

### ISSUE THREAD

**Issue by joedborg** [getsentry/docker-sentry#35]
See https://github.com/getsentry/sentry/issues/2549 for full story

```python
>>> mail.get_send_to(project)
[1]
```
...shows that I'm on the list.

Clicking "send test" on the Mail admin page works fine, as does
```python
project = Project.objects.get(slug='django')
message = MessageBuilder('test')
message.add_users((1,), project)
message.send()
```

But I never get emails for new events or regressions.

**Comment by mattrobenolt** [comment]
What are you using for smtp, out of curiosity? Since you need to either link an smtp container, or point to an external host.

**Comment by joedborg** [comment]
It's an external SMTP server

**Comment by mattrobenolt** [comment]
I will test this out today and verify that everything should be good, and we'll go from there. :)

**Comment by joedborg** [comment]
Thanks @mattrobenolt, let me know if you need anything.  For reference, this is my docker-compost file:

```yml
redis:
  image: redis

postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/data

sentry:
  image: sentry:latest
  environment:
    - SENTRY_EMAIL_HOST=(OMITTED)
    - SENTRY_SERVER_EMAIL=(OMITTED)
  links:
    - redis
    - postgres
  ports:
    - "9999:9000"

celery-beat:
  image: sentry:latest
  links:
    - redis
    - postgres
  command: sentry celery beat

celery-worker:
  image: sentry:latest
  links:
    - redis
    - postgres
  command: sentry celery worker
```

And just to confirm, I did a `docker pull sentry:latest` to ensure I'm at 8.0.2.

**Comment by joedborg** [comment]
Might have been fixed in 8.0.4; will test when sentry:latest is updated

**Comment by mattrobenolt** [comment]
Waiting on https://github.com/docker-library/official-images/pull/1368 :(

**Comment by joedborg** [comment]
Ah wow, I thought it was a mere docker push away!

**Comment by mattrobenolt** [comment]
Not for the official library, unfortunately. :(

--
Matt Robenolt
@mattrobenolt




On Mon, Jan 25, 2016 at 8:06 AM -0800, "Joe Borg" <notifications@github.com> wrote:












Ah wow, I thought it was a mere docker push away!

**Comment by joedborg** [comment]
8.0.4 hasn't fixed the issue unfortunately (have updated the HTTP server as well as Celery workers).

**Comment by mattrobenolt** [comment]
Alright. Will investigate more today. :(

--
Matt Robenolt
@mattrobenolt




On Tue, Jan 26, 2016 at 12:34 AM -0800, "Joe Borg" <notifications@github.com> wrote:












8.0.4 hasn't fixed the issue unfortunately (have updated the HTTP server as well as Celery workers).

**Comment by joedborg** [comment]
![notifications](https://cloud.githubusercontent.com/assets/1426404/12584582/230ccb5a-c440-11e5-9d05-627a68d5380a.png)
Not sure how relevant this is.

**Comment by Evede1** [comment]
Hello!
Just want to add, that it is not only mail notifications, slack-webhooks also cannot be sent now.

**Comment by mattrobenolt** [comment]
> slack-webhooks also cannot be sent now

And they did work before?

**Comment by Evede1** [comment]
It is just initial installation, so I cannot say about Sentry, but this web-hooks work fine on the other systems. It looks for me like something wrong with "rules", because it is possible to send invitations and test mails.

**Comment by mattrobenolt** [comment]
I finally got around to testing this, and I confirmed that this isn't working correctly for some reason.

Emails are sent from the web container, but not from celery containers. :( This seems odd, but at least I can reproduce.

**Comment by mattrobenolt** [comment]
@Evede1 @joedborg Does it work if you set an explicit `SENTRY_SECRET_KEY` environment variable on all the containers?

I'm still investigating the issue, but 90% sure if the worker and web containers have different secret keys, rules are failing to notify, but this seems odd to me.

If this is the case, I should be more explicit in documentation about setting and using SENTRY_SECRET_KEY. This is basically required, and maybe fail to start the process if there isn't one defined.

**Comment by mattrobenolt** [comment]
In 8.1, I've changed the behavior around this where a `SENTRY_SECRET_KEY` is required to be set. It will error otherwise starting up. This should help assert that all containers are in sync since you'd have to be explicit about passing this now.

**Comment by Evede1** [comment]
@mattrobenolt, unfortunately, I still cannot receive notifications, but after setting the `SENRY_SECRET_KEY` some activity is originated. The postfix logs doesn't contain any lines about these actions or errors.

![image](https://cloud.githubusercontent.com/assets/16960194/12712001/bd3233f2-c8d5-11e5-8453-5c3ae01f61af.png)

In the same time

![image](https://cloud.githubusercontent.com/assets/16960194/12712257/2299d69e-c8d8-11e5-9c99-3bec3d6e1efb.png)

**Comment by joedborg** [comment]
@mattrobenolt Can these be added as environments in the YML?

**Comment by joedborg** [comment]
```yml
edis:
    image: redis

postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/data

sentry:
  image: sentry
  environment:
    - SENTRY_EMAIL_HOST=(OMITTED)
    - SENTRY_SERVER_EMAIL=(OMITTED)
    - SENTRY_SECRET_KEY=(OMITTED)
  links:
    - redis
    - postgres
  ports:
    - "9999:9000"

celery-beat:
  image: sentry
  environment:
    - SENTRY_SECRET_KEY=(OMITTED)
  links:
    - redis
    - postgres
  command: sentry celery beat

celery-worker:
  image: sentry
  environment:
    - SENTRY_SECRET_KEY=(OMITTED)
  links:
    - redis
    - postgres
  command: sentry celery worker
```

I have used the same key for all 3.

**Comment by mattrobenolt** [comment]
@Evede1 do webhooks get delivered or any other notifications?

@joedborg which do you want in the yaml? All of these environment variables get handled by the sentry.conf.py now. It's not necessary that they exist in the yaml file.

**Comment by ocomsoft** [comment]
I had a similar issue turns out I need to add the smtp link to the celery containers ie 

```
docker run -d --name sentry-log --restart="always" -p 8081:9000  --link smtp:smtp --link sentry-redis:redis --link postgres:postgres -v /home/ocom/apps/sentry/files:/var/lib/sentry/files  sentry

docker run -d --restart="always" --name sentry-celery-beat --link postgres:postgres --link smtp:smtp --link sentry-redis:redis sentry celery beat

docker run -d --restart="always" --name sentry-celery1 --link postgres:postgres --link smtp:smtp  --link sentry-redis:redis sentry celery worker

```

**Comment by mattrobenolt** [comment]
@ocomsoft Did you only link them to the web container first?

Seems like we could clarify our documentation around here.

**Comment by ocomsoft** [comment]
Yes - I linked it to the Web container ran the test it worked!!

But I was NOT getting notifications... Tried adding it to Celery and BINGO..

I was going to raise an issue about the documentation because  Yes it could be clearer. But figured this might be a better place to mention it.

**Comment by mattrobenolt** [comment]
Ah, good to know.

I'm just going to assume these are all related to config issues.

I guess it's not obvious, but most of the work that Sentry does is handled by the workers. Much less is handled by the web process itself.

**Comment by Evede1** [comment]
@mattrobenolt, thank you! Mails notification works great, after setting were added for all containers.

**Comment by joedborg** [comment]
@mattrobenolt I just wanted to check that there was nothing obvious in the file.  Any other things I can investigate?

**Comment by mattrobenolt** [comment]
I have not been able to reproduce this in any way. :( The only thing I did notice is the default `From` email (`root@localhost`) tends to cause mail to get delivered to spam, but other than that, mail is always delivered in any configuration I've tried.

**Comment by frnknglrt** [comment]
The error mentioned in this issue is caused by the fact that the celery worker in the original docker-compose file does not use the intended email server. 

In order to fix this error, please make sure to set the follwing environment variables also for the sentry worker:
    - SENTRY_EMAIL_HOST=(OMITTED)
    - SENTRY_SERVER_EMAIL=(OMITTED)
    - SENTRY_SECRET_KEY=(OMITTED)



Like so: 


```
redis:
    image: redis

postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/data

sentry:
  image: sentry
  environment:
    - SENTRY_EMAIL_HOST=(OMITTED)
    - SENTRY_SERVER_EMAIL=(OMITTED)
    - SENTRY_SECRET_KEY=(OMITTED)
  links:
    - redis
    - postgres
  ports:
    - "9999:9000"

celery-beat:
  image: sentry
  environment:
    - SENTRY_SECRET_KEY=(OMITTED)
  links:
    - redis
    - postgres
  command: sentry celery beat

celery-worker:
  image: sentry
  environment:
    - SENTRY_SECRET_KEY=(OMITTED)
    - SENTRY_EMAIL_HOST=(OMITTED)
    - SENTRY_SERVER_EMAIL=(OMITTED)
  links:
    - redis
    - postgres
  command: sentry celery worker
```
