### ISSUE TITLE
No error data

### ISSUE THREAD

**Issue by Jastrzebowski** [getsentry/docker-sentry#72]
Hi,
I’m trying to run Sentry on DigitalOcean using Docker cloud, at first everything runs smooth but on error details page I find myself stuck with a “There was an error loading data.“ message and nothing in logs pointing to an error.

`Docker ps`:
```
c1b77a4ee076        sentry:8     sentry-celery1
497d3abe292d        sentry:8     sentry-celery-beat
24ed561acf1c        sentry:8     sentry-1.Sentry.xxx
a99d19dfd063        redis:3      redis-1.Sentry.xxx
8fb5a36fdaf1        postgres:9   postgres-1.Sentry.xxx
```

Docker stack file
```
postgres:
  environment:
    - POSTGRES_PASSWORD=sentry_passowrd
    - POSTGRES_USER=sentry_user
  image: 'postgres:9'
redis:
  image: 'redis:3'
sentry:
  environment:
    - 'SENTRY_SECRET_KEY=<sentry_key>'
  image: 'sentry:8'
  links:
    - postgres
    - redis
  ports:
    - '80:9000'
```
