### ISSUE TITLE
Remove deprecated ENV to make it docker-compose friendly

### ISSUE THREAD

**Issue by wernight** [getsentry/docker-sentry#79]
It looks like it currently uses deprecated environment variables like `REDIS_PORT_6379_TCP_ADDR` in `sentry.conf.py`: 

    redis = env('SENTRY_REDIS_HOST') or (env('REDIS_PORT_6379_TCP_ADDR') and 'redis')

This for example doesn't work when using `docker-compose.yml` equivalent to the started commands:

````
version: '2'
services:
  sentry:
    image: sentry
    links:
      - postgres
      - redis
    environment:
      - SENTRY_SECRET_KEY=<generated-secret>
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=secret
````

    $ docker-compose run --rm sentry upgrade
    sentry.runner.importer.ConfigurationError: Exception: Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?

Idea for a fix (but needs review):

    redis = env('SENTRY_REDIS_HOST', 'redis')

Same for other similar variables and then it works (tested by specifying `SENTRY_REDIS_HOST` **and** `SENTRY_POSTGRES_HOST` but also some that are not shared like `POSTGRES_ENV_POSTGRES_PASSWORD` and `POSTGRES_ENV_POSTGRES_USERNAME` and that makes a lot more sense).
